[package]
name = "minerva-mbedtls"
version = "0.3.3"
edition = "2018"
authors = ["ANIMA Minerva toolkit"]

[lib]
name = "minerva_mbedtls"

[features]
default = ["v3"]
v3 = ["psa-crypto"]
std = []

[dependencies]
mcu-if = { git = "https://github.com/AnimaGUS-minerva/mcu-if", rev = "984b8dd" }
psa-crypto = { git = "https://github.com/AnimaGUS-minerva/rust-psa-crypto", rev = "828695d", optional = true }

[build-dependencies]
cc = "1.0"
