[package]
name = "voucher-v3-x86-no_std"
version = "0.1.0"
edition = "2018"
authors = ["ANIMA Minerva toolkit"]

[dependencies]
minerva-mbedtls = { path = "../..", features = [] }
minerva-voucher = { git = "https://github.com/AnimaGUS-minerva/voucher", rev = "6e102be", default-features = false }
